name: Build Windows

on:
    push:
        # branches: [ "master" ]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: windows-2019

        steps:
            - uses: actions/checkout@v3

            - name: Cache nuget
              uses: actions/cache@v3
              with:
                  path: dist/packages
                  key: ${{ runner.os }}-nuget

            - name: Run build
              run: |
                  ./tools/windows/build.bat
              env:
                  CI: 1

            - name: Rename build
              id: "rename-build"
              shell: bash
              run: |
                  # check if a release branch, or master, or a tag
                  if [[ "${{ github.ref_name }}" == "master" || "${{ github.ref_name }}" == "2.3.x-lts" ]]
                  then
                    # Only proceed if we have an sftp password
                    if [ -n "${{ secrets.SFTP_PASSWORD }}" ]
                    then
                        TARGET=casparcg-server-${{ github.sha }}-windows.zip

                        mv dist/casparcg_server.zip "$TARGET"

                        echo "name=$TARGET" >> $GITHUB_OUTPUT
                    fi
                  fi

            - name: Copy single file to remote
              uses: garygrossgarten/github-action-scp@v0.8.0
              if: ${{ steps.rename-build.outputs.name }}
              with:
                  local: "${{ steps.rename-build.outputs.name }}"
                  remote: "${{ secrets.SFTP_ROOT }}/${{ github.ref_name }}/${{ steps.rename-build.outputs.name }}"
                  host: ${{ secrets.SFTP_HOST }}
                  username: ${{ secrets.SFTP_USERNAME }}
                  password: ${{ secrets.SFTP_PASSWORD }}
